version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.14
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: $DATABASE_PASSWORD
          POSTGRES_DB: clientorder
          SECRET_KEY: $SECRET_KEY
          POSTGRES_HOST_AUTH_METHOD: trust
          AFRICASTALKING_USERNAME: $AFRICASTALKING_USERNAME
          AFRICASTALKING_API_KEY: $AFRICASTALKING_API_KEY
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 3m 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run Migrations
          command: |
            . venv/bin/activate
            python manage.py migrate
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate 
            python manage.py test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/python:3.10.14
    steps:
      - attach_workspace:
          at: .
      - run:
        name: Install Node.js and npm
        command: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          sudo apt-get install -y nodejs
    - run:
        name: Install Render CLI
        command: npm install -g render-cli
      - run:
          name: Deploy to Render
          command: render deploy --service srv-cuf24s5ds78s73fetsdg

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
