version: 2.1

jobs:
  test:
    docker:
         - image: cimg/python:3.10.14
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install dependencies
          command: pipenv install --dev --deploy
      - run:
          name: Run Django migrations
          command: pipenv run python manage.py migrate
      - run:
          name: Run tests
          command: pipenv run python manage.py test

workflows:
  version: 2
  test:
    jobs:
      - test
