version: 2.1

jobs:
  test:
    docker:
         - image: cimg/python:3.10.14
          environment:
          SECRET_KEY:
    working_directory: ~/workspace
    
jobs:
  build:
    executor: python-executor
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Django Migrations
          command: python manage.py migrate
      - run:
          name: Run tests
          command: python manage.py test

workflows:
  version: 2
  build:
    jobs:
      - build
