version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.14
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      SECRET_KEY: $SECRET_KEY
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Django Migrations
          command: python manage.py migrate
      - run:
          name: Run tests
          command: python manage.py test

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "5432:5432"
